import os
import platform

"""
Definitions for common paths to configuration files.
"""

# General paths
ROOT_DIR = os.path.dirname(os.path.abspath(__file__))  # path to project root
# YAML
CONFIG_PATH = os.path.join(ROOT_DIR, 'configs/config.yaml')  # path to config.yaml
SENS_CONFIG_PATH = os.path.join(ROOT_DIR, 'configs/sensitive.yaml')  # path to sensitive_config.yaml
# LOGS
CHECKPOINT_PATH = os.path.join(ROOT_DIR, 'logs/checkpoints/')  # directory where models will be loaded and saved
EXAMPLES_PATH = os.path.join(ROOT_DIR, 'logs/train_examples/')  # directory where iteration train examples will be saved
GAME_HISTORY_PATH = os.path.join(ROOT_DIR, 'logs/game_history/')  # directory where arena SGF files will be saved
GRAPH_PATH = os.path.join(ROOT_DIR, 'logs/graphs/')  # directory where loss and win rate graphs will be saved
TRAIN_LOG_PATH = os.path.join(ROOT_DIR, 'logs/train_logs/')  # directory where detailed loss data (CSV) will be saved

# Paths only used for distributed training
DIS_STATUS_PATH = os.path.join(ROOT_DIR,
                               'distributed/')  # path to status.txt file, used to inform workers of current phase of training
DIS_SELF_PLAY_PATH = os.path.join(ROOT_DIR,
                                  'distributed/self_play/')  # path to location of games generated by linux workers

DIS_ARENA_PATH = os.path.join(ROOT_DIR,
                              'distributed/arena/')  # path to location of outcomes generated by linux workers

# Directory notation is different on Windows, change accordingly
if platform.system() == "Windows":
    CONFIG_PATH = os.path.join(ROOT_DIR, 'configs\\config.yaml')  # path to config.yaml
    SENS_CONFIG_PATH = os.path.join(ROOT_DIR, 'configs\\sensitive.yaml')  # path to sensitive_config.yaml
    EXAMPLES_PATH = os.path.join(ROOT_DIR, 'logs\\train_examples')  # path to checkpoint example files

    DIS_SELF_PLAY_PATH = os.path.join(ROOT_DIR, 'distributed\\self_play\\')
    DIS_ARENA_PATH = os.path.join(ROOT_DIR, 'distributed\\arena\\')
