title: AZ-Go
description: AlphaZero implementation for 7x7 Go with ResNet-18, Monte Carlo Tree Search, and distributed self-play training
theme: jekyll-theme-minimal
show_downloads: true
google_analytics:

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
author: Harrison
lang: en

# Navigation
navigation:
  - title: Home
    url: /
  - title: Installation
    url: /installation
  - title: Architecture
    url: /architecture
  - title: Training
    url: /training
  - title: Usage
    url: /usage
  - title: Analysis
    url: /analysis
  - title: References
    url: /references